### ISSUE TITLE
aalines vs lines

### ISSUE THREAD

**Issue by Devocub** [andrew12/osr-stuff#9]
use aalines instead lines, looks better

```
if tail:
        for points, color in lines:
            pygame.draw.aalines(screen, color, False, points)
```

**Comment by andrew12** [comment]
I used aalines before but I changed it to use lines instead. I don't remember if it was for performance or because it looked better though. Also I'm working on moving this project over to something that uses d3.js in the browser instead of pygame so I might not touch this again, unless there's issues with the parser.

**Comment by Devocub** [comment]
nvm, close
